services:

  db:
    container_name: fagskolen_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
      - "33060:33060"
    volumes:
      - db_data:/var/lib/mysql # Persist data in a named volume
    networks:
      - fagskolen_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: # Define the named volume for data persistence

networks:
  fagskolen_network:
    name: fagskolen_network
    driver: bridge